### ISSUE TITLE
[Homebridge UI] Error: Cannot find module 'fastify'

### ISSUE THREAD

**Issue by dcaccount** [oznu/homebridge-config-ui-x#1052]
Hello,

I have just tried to update the plugin but now I got the error:

> [Homebridge UI] Error: Cannot find module 'fastify'

What can I do? Please help.

Thanks,
Daniele

**Comment by oznu** [comment]
The npm update likely had an issue, re-installing should fix it:

```bash
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by dcaccount** [comment]
Thanks but it did not solve the problem, what can I try?

Please advise, thanks!

**Comment by oznu** [comment]
Can you provide full details of your setup and full logs and config.

```
* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
```

**Comment by dcaccount** [comment]
Yes, I will advise.

But how can I go back to the previous version?

**Comment by oznu** [comment]
https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions#using-the-command-line

**Comment by dcaccount** [comment]
Hello, can you please help me? I have tried to install the previous version but the problem continues.

The error is: 

> [Homebridge UI] Error: Cannot find module 'fastify'

The details are:

 Can you provide full details of your setup and full logs and config.
> 
> ```
> * **Node.js Version**:  11.15.0
> * **NPM Version**:  7.5.2.
> * **Homebridge Version**:  1.1.7
> * **Homebridge Config UI X Version**:
> * **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker: Raspbian
> * **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
> ```

**Comment by oznu** [comment]
Node.js v11.15.0 is not a supported version.

We only support v10, v12, and v14. Please update:

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

**Comment by dcaccount** [comment]
> Node.js v11.15.0 is not a supported version.
> 
> We only support v10, v12, and v14. Please update:
> 
> https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

Hello,
I have updated node js to version 14.15.4 but the problem continues:

> [3/2/2021, 11:21:36] Homebridge v1.2.4 is running on port 51826.
feb 03 11:21:36 rpinvr131 homebridge[558]: [3/2/2021, 11:21:36] [Homebridge UI] Error: Cannot find module 'fastify'
feb 03 11:21:36 rpinvr131 homebridge[558]: Require stack:
feb 03 11:21:36 rpinvr131 homebridge[558]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js
feb 03 11:21:36 rpinvr131 homebridge[558]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
feb 03 11:21:36 rpinvr131 homebridge[558]: [3/2/2021, 11:21:36] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
feb 03 11:21:36 rpinvr131 homebridge[558]: Error: Cannot find module 'fastify'
feb 03 11:21:36 rpinvr131 homebridge[558]: Require stack:
feb 03 11:21:36 rpinvr131 homebridge[558]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js
feb 03 11:21:36 rpinvr131 homebridge[558]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
feb 03 11:21:36 rpinvr131 homebridge[558]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at Module.require (internal/modules/cjs/loader.js:952:19)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at require (internal/modules/cjs/helpers.js:88:18)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at Object.76495 (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99573:18)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at __webpack_require__ (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99732:42)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at Object.48519 (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:79551:17)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at __webpack_require__ (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99732:42)
feb 03 11:21:36 rpinvr131 homebridge[558]:     at /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99760:18
feb 03 11:21:36 rpinvr131 homebridge[558]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99761:12) {
feb 03 11:21:36 rpinvr131 homebridge[558]:   code: 'MODULE_NOT_FOUND',
feb 03 11:21:36 rpinvr131 homebridge[558]:   requireStack: [
feb 03 11:21:36 rpinvr131 homebridge[558]:     '/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js',
feb 03 11:21:36 rpinvr131 homebridge[558]:     '/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'
feb 03 11:21:36 rpinvr131 homebridge[558]:   ]
feb 03 11:21:36 rpinvr131 homebridge[558]: }
feb 03 11:21:55 rpinvr131 homebridge[558]: ERROR: Large endpoint Cookie, removing endpointID => TV

Thanks for helping, Dan

**Comment by oznu** [comment]
Follow the instructions here to clean your system and start fresh (you won't loose Homebridge config):

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux
