### ISSUE TITLE
Failed to load config: Plugin alias could not be determined.

### ISSUE THREAD

**Issue by Luftloch80** [oznu/homebridge-config-ui-x#1089]
When Pressing bridge settings config ui says 
Failed to load config: Plugin alias could not be determined.
tried reeinstalling platform but no help
On homebridge 1.3.0

**Comment by donavanbecker** [comment]
@Luftloch80 Can you provide any info on your setup?

**Comment by Luftloch80** [comment]
Everything Is Running in one instance. I installed homebridge Beta two days ago and Added Child bridge manually because Ui did says

"You need to configure this plugin before you can manage it's bridge settings."

and after removing child bridge manually again UI says 
Failed to load config...

**Comment by oznu** [comment]
> Failed to load config: Plugin alias could not be determined.
 
If you maintain the offending plugin, an easy solution would be to add a "config.schema.json" file.

https://developers.homebridge.io/#/config-schema

If not, you will need to configure the child bridge settings manually. In the next release I will handle this in a better way, similar to what would be happening when you click the "Settings" button and it can't figure out the alias.

**Comment by Luftloch80** [comment]
Ah okay because Plugin Is Not configured for config-Uni-x. I Unterstand

**Comment by oznu** [comment]
> Ah okay because Plugin Is Not configured for config-Ui-x. I Understand

That, and the fallback method also couldn't figure out the alias.

**Comment by oznu** [comment]
Fixed in the next release. Window will now state this config needs to be done in the config editor.

**Comment by oznu** [comment]
@Luftloch80  what plugin was causing this issue?

**Comment by Luftloch80** [comment]
Homebridge-people-arp
Homebridge-synology 
And it is still present in 1.3.1

**Comment by oznu** [comment]
I meant this would be fixed in the next release of the UI; not Homebridge.

This release is still in test, see this link for info on how to lad the test version:

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by oznu** [comment]
Thanks for providing those plugins, I'll look into them and see if I can make the alias extractor work with them too.
