### ISSUE TITLE
limitation config

### ISSUE THREAD

**Issue by theo-69** [oznu/homebridge-config-ui-x#122]
I trieb to set uo a real long config file, however the plugin always removed part of it while saving it.

The config does have over 220 lines.

**Comment by theo-69** [comment]
Only thing I see `[Config] Invalid token sent by admin: invalid signature`

**Comment by oznu** [comment]
Can you share the config?

**Comment by theo-69** [comment]
its this one

```
    "bridge": {
        "name": "Aqara Gateway Oben",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": xxxxx,
        "pin": "xxx-xx-xxx"
    },
    "plugins": [
        "homebridge-config-ui-x",
        "homebridge-mi-aqara-mod"
    ],
    "accessories": [],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8095,
            "sudo": false,
            "restart": "sudo -n systemctl restart homebridge-aqara-oben",
            "log": {
                "method": "systemd",
                "service": "homebridge-aqara-oben"
            }
        },
        {
            "platform": "MiAqaraPlatform",
            "gateways": {
                "xxxxxxxxxx": "xxxxxxxxxx"
            },
            "defaultValue": {
                "34ce0088dac2": {
                    "Gateway_Lightbulb": {
                        "name": "Flur Gateway Licht"
                    },
                    "Gateway_LightSensor": {
                        "name": "Flur Lux Sensor"
                    },
                    "Gateway_Switch_JoinPermission": {
                        "name": "Flur Gateway join permission switch",
                        "disable": true
                    }
                },
                "158d00010d022b": {
                    "SingleWallButton_StatelessProgrammableSwitch": {
                        "name": "Flur Lichtschalter"
                    }
                },
                "158d000128ec57": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Test Button"
                    }
                },
                "158d0001832db0": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Büro Schreibtischlampen Eingang"
                    }
                },
                "158d0001831c98": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Wohnzimmer Stehlampen"
                    }
                },
                "158d00012a7f54": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Wohnzimmer Küchenlicht"
                    }
                },
                "158d0001831cd1": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Wohnzimmer Verandalampen"
                    }
                },
                "158d000128ccd9": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Schlafzimmer Eingang Nachttischlampen"
                    }
                },
                "158d0001831be5": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Schlafzimmer Kleiderschrank"
                    }
                },
                "158d0001831bf5": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Schlafzimmer Nachttisch Kai"
                    }
                },
                "158d00012a7dc3": {
                    "DuplexWallButton_StatelessProgrammableSwitch": {
                        "name": "Schlafzimmer Nachttisch Anja"
                    }
                },
                "158d0001a66841": {
                    "Button2_StatelessProgrammableSwitch": {
                        "name": "Schlafzimmer Paniklicht"
                    }
                },
                "158d0001a3f835": {
                    "Button_StatelessProgrammableSwitch": {
                        "name": "Schreibtisch Anja"
                    }
                },
                "158d000186f56d": {
                    "Button_StatelessProgrammableSwitch": {
                        "name": "Schreibtisch Kai"
                    }
                },
                "158d0001309b60": {
                    "Global": {
                        "serviceType": "Lightbulb"
                    },
                    "DuplexSwitch_Switch_Left": {
                        "name": "Büro Deckenventilator"
                    },
                    "DuplexSwitch_Switch_Right": {
                        "name": "Büro Deckenlicht"
                    }
                },
                "158d0001309b50": {
                    "Global": {
                        "serviceType": "Lightbulb"
                    },
                    "DuplexSwitch_Switch_Left": {
                        "name": "Schlafzimmer Wandlampen"
                    },
                    "DuplexSwitch_Switch_Right": {
                        "name": "Schlafzimmer Kleiderschrank"
                    }
                },
                "158d00012a7718": {
                    "Global": {
                        "serviceType": "Lightbulb"
                    },
                    "DuplexSwitch_Switch_Left": {
                        "name": "Bad Wandlampe"
                    },
                    "DuplexSwitch_Switch_Right": {
                        "name": "Bad Spiegellampe"
                    }
                },
                "158d0001309c13": {
                    "Global": {
                        "serviceType": "Lightbulb"
                    },
                    "DuplexSwitch_Switch_Left": {
                        "name": "Küche Deckenlampe"
                    },
                    "DuplexSwitch_Switch_Right": {
                        "name": "Küche Oberschränke"
                    }
                },
                "158d00012f79b3": {
                    "Global": {
                        "serviceType": "Lightbulb"
                    },
                    "DuplexSwitch_Switch_Left": {
                        "name": "Flur Aussenlicht"
                    },
                    "DuplexSwitch_Switch_Right": {
                        "name": "Flur Aussenlicht unten",
                        "disable": true
                    }
                },
                "158d00012f7942": {
                    "Global": {
                        "serviceType": "Lightbulb"
                    },
                    "DuplexSwitch_Switch_Left": {
                        "name": "Flur Deckenlicht Küche",
			"disable": true
                    },
                    "DuplexSwitch_Switch_Right": {
                        "name": "Flur Wandlampen"
                    }
                },
                "158d00021304a7": {
                    "WaterDetector_LeakSensor": {
                        "name": "Waschküche Wasser Leak"
                    }
                },
                "158d000155f14f": {
                    "ContactSensor_ContactSensor": {
                        "name": "Wohnzimmer Verandatür rechts"
                    }
                },
                "158d0001835425": {
                    "ContactSensor_ContactSensor": {
                        "name": "Wohnzimmer Verandatür links"
                    }
                },
                "158d00018355fa": {
                    "ContactSensor_ContactSensor": {
                        "name": "Flur Eingangstür"
                    }
                },
                "158d000152fbdf": {
                    "MotionSensor_MotionSensor": {
                        "name": "Außen Bewegungsmelder"
                    }
                },
                "158d00014ab157": {
                    "SingleSwitchLN_Switch": {
                        "name": "Abstellraum",
                        "disable": true
                    }
                },
                "158d00012a3699": {
                    "SingleSwitchLN_Switch": {
                        "name": "Waschküche"
                    }
                },
                "158d00013e2497": {
                    "PlugBase_Outlet": {
                        "name": "Alarmauslösung"
                    }
                }
            }
        }
    ]
    }
```

**Comment by oznu** [comment]
Is it cutting off the config resulting in invalid json or refusing to save?

**Comment by theo-69** [comment]
It is pretending to safe if I add one item like
```
,
                "158d00013e2497": {
                    "PlugBase_Outlet": {
                        "name": "Alarmauslösung"
                    }
                }
```
but then its returning and the item is not there anymore, thats kind of annoying if you have to add several of them. It started after 20 items or so. If I add them manually via VNC its working fine. Config is working 100%

**Comment by oznu** [comment]
I've pushed up a change to make the whole config saving process more robust.

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

* Sync config.json file saves, rather than async
* UI will not allow save to be hit multiple times
* UI will go into read only while save is in progress

You can also use CTRL+S / CMD+S while focused on the config editor for quick saving.

**Comment by theo-69** [comment]
Just tried it, still the same. If I have a long config and hit save even without changing anything it will be shortened. :-(

**Comment by theo-69** [comment]
my mistake used one ID twice (copy&paste)
