### ISSUE TITLE
Font Awesome v7 Icon Issues

### ISSUE THREAD

**Issue by cheetahbridge3** [oznu/homebridge-config-ui-x#2511]
### Describe The Bug

None of the sidebar icons are visible either when hovering on sidebar or in its condensed view. 

<img width="252" height="791" alt="Image" src="https://github.com/user-attachments/assets/e465f38d-c821-4b62-8fd8-83f5ba7c5707" />

Bridge icons also not visible:

<img width="428" height="185" alt="Image" src="https://github.com/user-attachments/assets/f7c2ad9f-7166-40eb-822a-00ee4d3f5ee2" />

No icons present in other sub pages for example the Support page.
<img width="1435" height="752" alt="Image" src="https://github.com/user-attachments/assets/d23385b7-2005-4c4b-88be-80d0c293346f" />

All icons in v5.2.0 are visible (I reverted to confirm).

### Logs

not relevant

### Config

```JSON
not relevant
```

### Homebridge UI Version

5.3.0

### Homebridge Version

1.11.0

### Node.js Version

v22.17.1

### Operating System

macOS

### Environment Info

None

### Raspberry Pi Model

None

**Comment by joshuaseltzer** [comment]
Same issue here.

**Comment by bwp91** [comment]
please can someone try the beta version to confirm this has been resolved?

**Comment by joshuaseltzer** [comment]
Icons are all still missing for me on Beta 16.

I'm guessing something changed which requires a later version of WebKit because I'm experiencing this issue specifically on my iOS devices on iOS 15.x.

Also, this started with 5.3.0. If I roll back to 5.2.0, the icons return.

**Comment by bwp91** [comment]
> Icons are all still missing for me on Beta 16.
> 
> I'm guessing something changed which requires a later version of WebKit because I'm experiencing this issue specifically on my iOS devices on iOS 15.x.
> 
> Also, this started with 5.3.0. If I roll back to 5.2.0, the icons return.

I believe this is a cache issue between an upgrade of the library that provides the icons. If you update to 5.3.0 again, and use your browsers 'private tab'/'incognito tab' can you access the UI, login, and see if the icons appear?

**Comment by joshuaseltzer** [comment]
> > Icons are all still missing for me on Beta 16.
> > 
> > I'm guessing something changed which requires a later version of WebKit because I'm experiencing this issue specifically on my iOS devices on iOS 15.x.
> > 
> > Also, this started with 5.3.0. If I roll back to 5.2.0, the icons return.
> 
> I believe this is a cache issue between an upgrade of the library that provides the icons. If you update to 5.3.0 again, and use your browsers 'private tab'/'incognito tab' can you access the UI, login, and see if the icons appear?

Nope, same issue.

I can provide JavaScript logs if that would be helpful.

**Comment by bwp91** [comment]
This looks very suspect: 
- https://github.com/FortAwesome/Font-Awesome/issues/20727

**Comment by joshuaseltzer** [comment]
Yes to me that sounds like exactly what we're experiencing here. Does HomeBridge UI use the same JavaScript that would be causing that issue?

Also I tried checking the logs from my device but no errors are reported in the logs.

**Comment by bwp91** [comment]
Could you try the most recent beta? I’ve applied the patch fix included in one of the posts on that other issue link. we can see how it goes! @joshuaseltzer

**Comment by joshuaseltzer** [comment]
> Could you try the most recent beta? I’ve applied the patch fix included in one of the posts on that other issue link. we can see how it goes! @joshuaseltzer 

Still an issue on Beta 20 unfortunately.

**Comment by bwp91** [comment]
if you didn’t already, please can you try clearing your cache for this site, or trying in an incognito window or different browser?

(i mean on the newest beta)

**Comment by joshuaseltzer** [comment]
> if you didn’t already, please can you try clearing your cache for this site, or trying in an incognito window or different browser?
> 
> (i mean on the newest beta)

Same result. I tried both clearing the cache and a private window.

Interestingly, as soon as I reinstall 5.2.0, even on the "restarting" screen the icons will be working again.

**Comment by cheetahbridge3** [comment]
Same. Latest beta after cleared cache and also in private windows still doesn't work. 

Reverting to 5.2.0 immediately restores all the icons.

**Comment by joshuaseltzer** [comment]
> Same. Latest beta after cleared cache and also in private windows still doesn't work.
> 
> Reverting to 5.2.0 immediately restores all the icons.

Are you also testing on Safari 15.x?

**Comment by bwp91** [comment]
@joshuaseltzer @cheetahbridge3  do you have any errors in your browser developer console when you are on 5.3.0?

**Comment by cheetahbridge3** [comment]
Most likely yes? Sorry it will be a day or two until I can confirm as we lost power and it isn’t estimated for restoration for another 1-2 days :(

I am running my homebridge on a late 2013 MacBook Pro whose latest OS is macOS 11.17.10 and whichever latest Safari version that supports, which is possibly Safari 16.6.1

**Comment by TheRealWolfpunk** [comment]
This is the output from Firefox' 115.26.0esr (64-Bit) on Mac OS 10.13.6.

homebridge-config-ui-x Version: **5.3.1 beta 23**

Version 5.2.0 shows all icons, version 5.3.0 and above doesn't display any icons, as described in the posts above.

> Browser-Konsolenmodus
> Multiprozess(Langsamer)
> 14:09:04.940 Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("default-src"). 4 customElements.js:499:24
> 14:09:04.940 Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("default-src"). 2 panel.js:62:22
> 14:09:05.070
> TypeError: currentNode is null
>     canMutationImpactCurrentStyles resource://devtools/client/inspector/shared/style-change-tracker.js:66
>     onMutations resource://devtools/client/inspector/shared/style-change-tracker.js:84
>     _emit resource://devtools/shared/event-emitter.js:242
>     emit resource://devtools/shared/event-emitter.js:186
>     emit resource://devtools/shared/event-emitter.js:330
>     getMutations resource://devtools/client/fronts/walker.js:309
> event-emitter.js:257:19
> 14:09:05.172
> AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved ConduitsParent.sys.mjs:362
> 14:09:05.294
> Promise resolved after context unloaded
> bootstrap-autofill-overlay.js:185
> 14:09:06.351 unreachable code after return statement
> chunk-TIL3AXXZ.js:4:56516
> 14:09:06.707 Use of nsIFile in content process is deprecated. 15 NetUtil.sys.mjs:249:8
> 14:09:07.243
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.244
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.245
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.245
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.247
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.247
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.248
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.248
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.249
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.249
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.250
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.250
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.251
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.251
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.252
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.253
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.253
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.254
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:07.280 Use of nsIFile in content process is deprecated. 7 NetUtil.sys.mjs:249:8
> 14:09:07.964
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:07.965
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:08.056 Use of nsIFile in content process is deprecated. NetUtil.sys.mjs:249:8
> 14:09:08.808
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:08.809
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:08.809
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:08.810
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:08.810
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:08.811
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:08.811
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:08.812
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:08.812
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:08.813
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.051
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.052
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.204
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.204
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.205
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.205
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.206
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.207
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.208
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.208
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.209
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.209
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:09.210
> [COMPATIBILITY_APPEND_NODE_FAILURE] Target already destroyed, unable to fetch children fronts compatibility.js:255:11
> 14:09:09.210
> getFront@resource://devtools/client/fronts/targets/target-mixin.js:241:15
> appendNode/<@resource://devtools/client/inspector/compatibility/actions/compatibility.js:58:47
> thunk/</</<@resource://devtools/client/shared/redux/middleware/thunk.js:17:11
> _onMarkupMutation@resource://devtools/client/inspector/compatibility/CompatibilityView.js:203:30
> _emit@resource://devtools/shared/event-emitter.js:242:32
> emit@resource://devtools/shared/event-emitter.js:186:18
> emit@resource://devtools/shared/event-emitter.js:330:18
> _onWalkerMutations/<@resource://devtools/client/inspector/markup/markup.js:1594:22
> compatibility.js:256:11
> 14:09:10.156 Use of nsIFile in content process is deprecated. 76 NetUtil.sys.mjs:249:8

**Comment by TheRealWolfpunk** [comment]
Additional output in the console is:

> unreachable code after return statement chunk-TIL3AXXZ.js:4:56516 (***/chunk-TIL3AXXZ.js)
> Error: Promised response from onMessage listener went out of scope ExtensionMessagingService.js:89:34(moz-extension://93ee6444-81c1-494d-888e-fa3a93810a22/scripts/services/ExtensionMessagingService.js)

That "chunk" error links to this page: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Errors/Stmt_after_return?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

Please let me know if I can provide any more useful information.

**Comment by bwp91** [comment]
please try the beta 24. i have reverted fontawesome library back to v6

**Comment by cheetahbridge3** [comment]
Fixed! Looks good with that beta version.

**Comment by joshuaseltzer** [comment]
> please try the beta 24. i have reverted fontawesome library back to v6

Confirmed working for me on my devices. That seemed to be the culprit.

**Comment by TheRealWolfpunk** [comment]
Thanks! Fixed for me as well. Thumbs up!

**Comment by joshuaseltzer** [comment]
@bwp91 someone in that fontawesome issue you linked earlier made a comment (https://github.com/FortAwesome/Font-Awesome/issues/20727#issuecomment-3129514141) mentioning how the problematic plugin, `PseudoElements`, can selectively be omitted from the project as long as it's not used. I haven't looked at the Homebridge UI code close enough to know if it's required, but if not, maybe that's a better solution than downgrading.

Here's a demo project created by the user who made that suggestion in the issue above: https://github.com/mlwilkerson/fa-svg-without-pseudo-elements

**Comment by bwp91** [comment]
I think generally the ‘issue’ here is that font awesome only supports the last two major versions of browsers:
- https://docs.fontawesome.com/web/dig-deeper/browser-support

At some point in the future it would be nice to update to the latest version, but i'm happy to stay at v6 for now.

**Comment by bwp91** [comment]
Hi @cheetahbridge3 @joshuaseltzer 

I've reopened this as there was an update to font-awesome v7 which contains some fixes.

I was hoping that one of you could try to update to the UI beta (v5.5.1-beta.5) to see if the icon issue is now fixed on iOS devices on iOS 15.x.

Let me know what the result is if you get the chance, thanks!

**Comment by cheetahbridge3** [comment]
@bwp91 all looks good for me in v5.5.1-beta.5

<img width="248" height="434" alt="Image" src="https://github.com/user-attachments/assets/642dfad5-867b-4aa8-ba2a-22b9ea4bdf03" />

**Comment by joshuaseltzer** [comment]
Also working for me on my iOS 15 device (iOS 15.1.1). Looks like they fixed it.

**Comment by bwp91** [comment]
great news! thank you both for checking

**Comment by bwp91** [comment]
fixed (again!) in 5.6.0
