### ISSUE TITLE
Node.js 12 Support

### ISSUE THREAD

**Issue by marcoschmidt79** [oznu/homebridge-config-ui-x#277]
Error with node v12.1.0

Apr 29 18:21:40 homebridge homebridge[1812]: [2019-4-29 18:21:40] [homebridge-config-ui-x] Error: Cannot find module '../build/Debug/pty.node'
Apr 29 18:21:40 homebridge homebridge[1812]: Require stack:
Apr 29 18:21:40 homebridge homebridge[1812]: - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/utils.js
Apr 29 18:21:40 homebridge homebridge[1812]: - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
Apr 29 18:21:40 homebridge homebridge[1812]: - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
Apr 29 18:21:40 homebridge homebridge[1812]: - /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
Apr 29 18:21:40 homebridge homebridge[1812]: - /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js

**Comment by oznu** [comment]
Related upstream issue:

```
https://github.com/Microsoft/node-pty/issues/279
```

**Comment by oznu** [comment]
### Node.js 12 is not supported by this plugin until the issue above is resolved.

**Comment by robertgranholm** [comment]
Shoot...upgraded node to get ffmeg homebridge plugin working and then ran into this....waiting in the wings for Node 12 support

**Comment by realdannys** [comment]
Damn, me too.

**Comment by oznu** [comment]
This should be resolved in 4.4.1 which is in beta. I'm looking for a couple people to test this before publishing to everyone.

The beta release can be installed with this command:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

**Comment by marcoschmidt79** [comment]
> This should be resolved in 4.4.1 which is in beta. I'm looking for a couple people to test this before publishing to everyone.

Hello, thats great, i tasted with node 12.2.0 and config-ui-x 4.4.1-beta.1 and it works perfectly. thank you very much.

**Comment by robertgranholm** [comment]
Hmm I installed the beta, homebridge started it up okay, no errors this time, however I still get a 402 bad gateway when trying to load the ui address. Here's load up - http://getsupport.itarsenal.com/snaps/Monosnap_2019-05-14_10-41-20.png

**Comment by oznu** [comment]
@robertgranholm 502 bad gateway? That sounds like a reverse proxy issue.

**Comment by oznu** [comment]
Resolved in v4.4.1

**Comment by RMCob** [comment]
Updated to 4.4.1. Then updated node from 8.16 to 12.2.
Got the **Cannot find module '../build/Debug/pty.node'** error.
Reverted node back to 8.16 and everything ok.

**Comment by marcoschmidt79** [comment]
update first node and then config-ui-x

**Comment by RMCob** [comment]
Not sure what you mean by "npm rebuild".
I totally removed homebridge-config-ui-x and nodejs. Installed the latest node (12.2) via apt-install.
Installed the latest homebridge-config-ui-x via npm. Still get the same error. When I revert nodejs back to 8.16 homebridge-config-ui-x starts with no issues.

**Comment by marcoschmidt79** [comment]
please open new issue with your problem and log from install and homebridge-start. my problem is not your problem

**Comment by janthony6** [comment]
I get the same error.

[5/16/2019, 21:40:23] [homebridge-config-ui-x] Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js

**Comment by oznu** [comment]
If you're getting `pty.node` errors, then the npm command would have errored out during the fresh installation of the plugin you did after upgrading a major node.js version.

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by janthony6** [comment]
still crashing after trying that but with less errors.  getting this:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by janthony6** [comment]
okay i figured it out.  nest was busted on node 12

**Comment by pasna** [comment]
Hi,
Any news on error fixed for node12?

**Comment by oznu** [comment]
This was fixed some time ago.

**Comment by mentaluproar** [comment]
Not fixed for me.  Same problem.

**Comment by oznu** [comment]
After doing a major version upgrade you need to rebuild or reinstall:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by mentaluproar** [comment]
tried rebuild.  didn't work.  Tried removing and reinstalling.  didn't work.

**Comment by oznu** [comment]
@mentaluproar raise an issue and I'll see what I can do to help - https://github.com/oznu/homebridge-config-ui-x/issues/new?assignees=&labels=question&template=support-request.md

**Comment by mentaluproar** [comment]
I removed the plugin and tried launching again.  Homebridge still tries to load it, even though its not installed and its not in the config.json.  I'm going to dig a little more.  It's possible this problem is my rig and not your plugin.

**Comment by mentaluproar** [comment]
Yea, node is totally broken on my system.  Ignore this.  Sorry.
