### ISSUE TITLE
Translations for Accessory state

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#342]
Hi,

It would be nice add translations for accessory state, now we have only EN.

Thanks

**Comment by oznu** [comment]
Good idea. There shouldn't be too many new words to translate.

**Comment by mafyata** [comment]
We will translate it fast. I translated hoobs BG language for 1 hour.

**Comment by oznu** [comment]
I've added support for this and created placeholders for all the keys that need translating in each language file.

https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/i18n/en.json#L17-L39

For details on how to get a development environment setup so you can preview your translations in-app see https://github.com/oznu/homebridge-config-ui-x/blob/master/CONTRIBUTING.md.

**Comment by oznu** [comment]
```json
    "accessories.control.label_on": "On",
    "accessories.control.label_off": "Off",
    "accessories.control.label_open": "Open",
    "accessories.control.label_closed": "Closed",
    "accessories.control.label_opening": "Opening",
    "accessories.control.label_closing": "Closing",
    "accessories.control.label_stopped": "Stopped",
    "accessories.control.label_locked": "Locked",
    "accessories.control.label_unlocked": "Unlocked",
    "accessories.control.label_jammed": "Jammed",
    "accessories.control.label_unknown": "Unknown",
    "accessories.control.label_triggered": "Triggered",
    "accessories.control.label_heat": "Heat",
    "accessories.control.label_cool": "Cool",
    "accessories.control.label_auto": "Auto",
    "accessories.control.label_rotation_speed": "Rotation Speed",
    "accessories.control.label_brightness": "Brightness",
    "accessories.control.label_set_to": "Set to",
    "accessories.control.label_target": "Target",
    "accessories.control.label_target_temperature": "Target Temperature",
    "accessories.control.label_fan": "Fan",
    "accessories.control.label_light": "Light",
    "accessories.control.not_supported": "Not Supported",
```

**Comment by grzegorz914** [comment]
Hi,

updated to beta22 and Accessory - Thermostat Mode off are not translated.

Thanks

**Comment by Caribsky** [comment]
Same problem with Thermostat. 
Aslo Homebridge restart page not translated too. 
![Снимок экрана 2019-08-08 в 16 36 20](https://user-images.githubusercontent.com/37780308/62703658-b881fd00-b9fa-11e9-9476-870725676fab.png)

**Comment by grzegorz914** [comment]
Also „Default Room” need to be translated.

**Comment by oznu** [comment]
I've fixed the thermostat `Off` label and added a key for "Default Room".

**Comment by Caribsky** [comment]
@oznu 
By the way… Thermostat window with translation too small
![Снимок экрана 2019-08-08 в 16 36 10](https://user-images.githubusercontent.com/37780308/62706797-46f97d00-ba01-11e9-8e75-e3d6f52cc277.png)

**Comment by oznu** [comment]
@Caribsky - I can stack them vertically.

![image](https://user-images.githubusercontent.com/3979615/62707364-91482180-ba34-11e9-8d94-d3804e3e0339.png)

**Comment by Caribsky** [comment]
I like this layout. Looks like as on iPhone. 
Also I need fix translation for thermostat.

**Comment by oznu** [comment]
The beta has been updated with your pull requests and the other changes made.

**Comment by Caribsky** [comment]
@oznu 
I don't see any accessories and rooms after this update.
cache deleted in Safari.. :(

**Comment by Caribsky** [comment]
Sorry, @oznu 
Looks like it's my local problem with Safari. 
All OK in Firefox.

**Comment by oznu** [comment]
You had me worried. I'll check out Safari tomorrow to make sure it's all ok.

**Comment by grzegorz914** [comment]
Im on safari macOSX Catalina b5, all is displayed OK, except state of thermostat.
<img width="1815" alt="Zrzut ekranu 2019-08-8 o 19 26 56" src="https://user-images.githubusercontent.com/28867813/62724139-972d0b00-ba12-11e9-8769-611107817093.png">

**Comment by mafyata** [comment]
Bulgarian language translation. It is in zip because I can't upload json file here.

[bg.zip](https://github.com/oznu/homebridge-config-ui-x/files/3483404/bg.zip)

**Comment by tooh** [comment]
I,m on EN
Accessories spelled wrong
Homebridge Accessores

**Comment by oznu** [comment]
Hi @tooh,

The only instance of the word `Accessores` is in the NL translation?

https://github.com/oznu/homebridge-config-ui-x/search?q=Accessores&unscoped_q=Accessores

**Comment by tooh** [comment]
Hm strange was not aware that it uses Nl as language. But you’re right.

Translation should be:

accessoires

**Comment by Caribsky** [comment]
Hi @oznu,
Could you please update beta.. i can't fetch last merged translation fix in ru.json. 
Thanks

Also, regarding Thermostat window. The accessory box start dragging when click on Thermostat in Firefox (mac os), please see screenshot below. 

![Снимок экрана 2019-08-09 в 16 10 01](https://user-images.githubusercontent.com/37780308/62778072-5ab7e880-bac0-11e9-9e3c-c2f676eb8b54.png)

**Comment by oznu** [comment]
@Caribsky, I'll update the beta soon and let you know.

Regarding the thermostat window, you need to start moving your mouse within 350 ms otherwise it detects a "long press" and opens up the modal. I've just tested this on the latest versions of Firefox, Safari and Chrome on macOS.

**Comment by oznu** [comment]
@tooh, updated, thanks.

**Comment by Caribsky** [comment]
@oznu 
It's really strange.. I have last stable versions of Firefox, Safari and Chrome. Only in Firefox appeared this bug and it's doesn't depend from delay of start moving mouse, after 1 sec or 10 sec.
Just tried to test it on other Windows computer.. same problem with Firefox. :(

**Comment by oznu** [comment]
@Caribsky, i think i misunderstood the issue you described. I thought you were saying when you were trying to move the tiles, the modal was showing, but you mean when you are trying to open the modal, the tile starts moving?

**Comment by Caribsky** [comment]
@oznu, in other words ... the tile starts following the cursor after showing the modal window.

**Comment by oznu** [comment]
I can't figure this one out right now @Caribsky, I'll try again later, as a work around you can toggle the layout lock:

![image](https://user-images.githubusercontent.com/3979615/62783652-2c59fd80-bb00-11e9-9208-45924eeb9f58.png)

**Comment by Caribsky** [comment]
Thanks, @oznu 
Toggle the layout lock is good idea, it's helped.

**Comment by oznu** [comment]
@Caribsky, I fixed the Firefox modal and drag issue in the latest beta.

**Comment by Caribsky** [comment]
> @Caribsky, I fixed the Firefox modal and drag issue in the latest beta.

Works good!
Thank you, @oznu!

**Comment by grzegorz914** [comment]
One word still not translated: "End Process"
![IMG_0062](https://user-images.githubusercontent.com/28867813/62819013-a665a300-bb4f-11e9-84f0-ad69d4c3feba.jpeg)

**Comment by oznu** [comment]
Thanks @grzegorz914, that bit of text is is sent directly from the server as a debug message, so it doesn't get translated. I don't have any plans to add internationalisation to the server side any time soon (this includes all logs, or error / debug messages sent from the server like the one above).

**Comment by grzegorz914** [comment]
@oznu 
ok its clear.

**Comment by oznu** [comment]
I just pushed up a new beta, with dark mode off-state tiles. I'm not sure how to handle on-state tiles in dark mode yet, I'll probably wait until I can see how iOS 13 dark mode does it.

**Comment by oznu** [comment]
It broke light mode on-state of course, should have tested, fixing it now.

**Comment by oznu** [comment]
Thanks everyone for your help one this one.
