### ISSUE TITLE
Failed to load node-pty module (Homebridge no longer starts)

### ISSUE THREAD

**Issue by Neejoh** [oznu/homebridge-config-ui-x#514]
**Describe The Bug:**

When I try to start Homebridge it can't go through because of an error.
It used to work flawlessly but a couple hours back I've installed Home Assistant on my Raspberry Pi 4. I guess that changed the NodeJS version from 'something' (don't remember) to v12.14.1
According to your readme that should suffice, as long as it is > v10.x

I'm getting an error that `[1/29/2020, 11:00:49 PM] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node` should be rebuild, which I have tried through the steps described in the error log (see below). 

I have also tried uninstalling and re-installing Config UI X with no different result.

I have no idea what the versions are that are mentioned in the log (VERSION 64 and 72).

**To Reproduce:**

**Expected behavior:**

I expect systemctl to be able to run homebridge without having to retry every 10 seconds

**Logs:**

```
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] Got SIGTERM, shutting down Homebridge...
jan 29 23:00:49 raspi homebridge[4147]: innerError Error: Cannot find module '../build/Debug/pty.node'
jan 29 23:00:49 raspi homebridge[4147]: Require stack:
jan 29 23:00:49 raspi homebridge[4147]: - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
jan 29 23:00:49 raspi homebridge[4147]: - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
jan 29 23:00:49 raspi homebridge[4147]: - /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
jan 29 23:00:49 raspi homebridge[4147]: - /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
jan 29 23:00:49 raspi homebridge[4147]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
jan 29 23:00:49 raspi homebridge[4147]:     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
jan 29 23:00:49 raspi homebridge[4147]:     at Module.require (internal/modules/cjs/loader.js:848:19)
jan 29 23:00:49 raspi homebridge[4147]:     at require (internal/modules/cjs/helpers.js:74:18)
jan 29 23:00:49 raspi homebridge[4147]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:30:15)
jan 29 23:00:49 raspi homebridge[4147]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
jan 29 23:00:49 raspi homebridge[4147]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
jan 29 23:00:49 raspi homebridge[4147]:     at Module.load (internal/modules/cjs/loader.js:811:32)
jan 29 23:00:49 raspi homebridge[4147]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
jan 29 23:00:49 raspi homebridge[4147]:     at Module.require (internal/modules/cjs/loader.js:848:19) {
jan 29 23:00:49 raspi homebridge[4147]:   code: 'MODULE_NOT_FOUND',
jan 29 23:00:49 raspi homebridge[4147]:   requireStack: [
jan 29 23:00:49 raspi homebridge[4147]:     '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
jan 29 23:00:49 raspi homebridge[4147]:     '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js',
jan 29 23:00:49 raspi homebridge[4147]:     '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
jan 29 23:00:49 raspi homebridge[4147]:     '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'
jan 29 23:00:49 raspi homebridge[4147]:   ]
jan 29 23:00:49 raspi homebridge[4147]: }
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
jan 29 23:00:49 raspi homebridge[4147]: was compiled against a different Node.js version using
jan 29 23:00:49 raspi homebridge[4147]: NODE_MODULE_VERSION 64. This version of Node.js requires
jan 29 23:00:49 raspi homebridge[4147]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
jan 29 23:00:49 raspi homebridge[4147]: the module (for instance, using `npm rebuild` or `npm install`).
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] Node.js v12.14.1
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] Failed to load node-pty module
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version and have not reinstalled or rebuilt this plugin.
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] This can usually be fixed by uninstalling and reinstalling this homebridge-config-ui-x
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] From the terminal run these commands (exact commands may vary):
jan 29 23:00:49 raspi homebridge[4147]: 
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] sudo npm uninstall -g homebridge-config-ui-x
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] sudo npm install -g --unsafe-perm homebridge-config-ui-x
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] cd $(sudo npm -g prefix)/lib/node_modules
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] sudo npm rebuild --unsafe-perm
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "AA:BB:CC:11:22:33",
        "port": 51826,
        "pin": "432-11-234"
    },
    "description": "Home config",
    "ports": {
        "start": 52100,
        "end": 52150
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8888,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "loginWallpaper": "/home/pi/.homebridge/living-room.jpg",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        },
        {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": "---------",
                "cookies": "---------",
                "apiKey": "---------"
            }
        }
    ],
    "accessories": []
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v12.14.1
* **NPM Version**:  6.13.7
* **Homebridge Version**:  0.4.50
* **Homebridge Config UI X Version**: 1.1.5
* **Operating System**: Raspbian Pi 4, 4G, 32GB @ SD
* **Process Supervisor**: Systemd

Kind of need help with this one, many thanks in advance.

**Comment by oznu** [comment]
Did you try this?

```
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] Failed to load node-pty module
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version and have not reinstalled or rebuilt this plugin.
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] This can usually be fixed by uninstalling and reinstalling this homebridge-config-ui-x
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] [node-pty] From the terminal run these commands (exact commands may vary):
jan 29 23:00:49 raspi homebridge[4147]: 
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] sudo npm uninstall -g homebridge-config-ui-x
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] sudo npm install -g --unsafe-perm homebridge-config-ui-x
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] cd $(sudo npm -g prefix)/lib/node_modules
jan 29 23:00:49 raspi homebridge[4147]: [1/29/2020, 11:00:49 PM] [Config] sudo npm rebuild --unsafe-perm
```

**Comment by FouFouCode** [comment]
I've got the same problem (same versions/env, except RPi3 1G).
I deinstalled/reinstalled homebridge-config-ui, rebuilt /lib/node_modules.
Still not working.

**Comment by Neejoh** [comment]
Yes, I tried reinstalling and rebuilding like the error log mentioned. Hasn’t fixed it.

Also, the ‘sudo npm uninstall’ still leaves the directories on the system as if it is installed, but it actually says it successfully uninstalled it.

**Comment by oznu** [comment]
Try rebuilding just this plugin:

```
cd /usr/local/lib/node_modules/homebridge-config-ui-x
sudo npm rebuild
```

**Comment by FouFouCode** [comment]
There are some errors during rebuild:

`/usr/local/lib/node_modules/homebridge-config-ui-x $ sudo npm rebuild

> @nestjs/core@6.11.4 postinstall /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/core
> opencollective || exit 0

                          Thanks for installing nest 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 406
                              Number of backers: 286
                              Annual budget: $63,084
                             Current balance: $5,398

       👉  Become a partner: https://opencollective.com/nest/donate


> node-pty-prebuilt-multiarch@0.9.0 install /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-01T07_27_22_919Z-debug.log
`
I uninstalled homebridge-config-ui-x , checked that the folder homebridge-config-ui-x was effectively removed from /usr/local/lib/node_modules, reinstalled it and tried again the rebuild. Same error.

**Comment by oznu** [comment]
Sorry,

```
cd /usr/local/lib/node_modules/homebridge-config-ui-x
sudo npm rebuild --unsafe-perm
```

**Comment by Neejoh** [comment]
That did it! My npm -g prefix returns /usr, not /usr/local

Thanks for the tip @oznu, I hope it works for @FouFouCode too.

**Comment by FouFouCode** [comment]
Problem is solved too for me.
In fact, I had 2 installations of config ui, one in /usr/lib and the other in /usr/local/lib. I deinstalled both of them, and reinstalled from github. This solved the issue.
Thanks for help!

**Comment by oznu** [comment]
Great. The nest release of this plugin will attempt to rebuild automatically after a Node.js update which should prevent many issues similar to this in the future.

**Comment by ItsNaud** [comment]
Hello,

Unfortunately I still experience this issue. First on an existing installation, after that I re-installed Raspbian and Homebridge.

**Environment:**

**Node.js Version:** v12.16.3
**NPM Version:** 6.14.5
**Homebridge Version:** 1.0.4
**Homebridge Config UI X Version:** 4.18.0

`[5/12/2020, 3:59:01 PM] Homebridge is running on port 51826.
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'
  ]
}
[5/12/2020, 3:59:02 PM] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
[5/12/2020, 3:59:02 PM] [Config] [node-pty] Node.js v12.16.3
[5/12/2020, 3:59:02 PM] [Config] [node-pty] Failed to load node-pty module
[5/12/2020, 3:59:02 PM] [Config] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
[5/12/2020, 3:59:02 PM] [Config] [node-pty] Follow the steps below to resolve this issue.
[5/12/2020, 3:59:02 PM] [Config] [node-pty] Trying to rebuild automatically...
[5/12/2020, 3:59:26 PM] [Config] [node-pty] Module rebuilt successfully (maybe) - if you are still encountering errors follow the steps below.
[5/12/2020, 3:59:26 PM] [Config] [node-pty] From the terminal run these commands (exact commands may vary):

[5/12/2020, 3:59:26 PM] [Config] cd /usr/local/lib/node_modules/homebridge-config-ui-x
[5/12/2020, 3:59:26 PM] [Config] sudo npm rebuild --unsafe-perm

[5/12/2020, 3:59:26 PM] Got SIGTERM, shutting down Homebridge...
`

Also when I try to rebuild the plugin with the following it don't solve the problem:

`cd /usr/local/lib/node_modules/homebridge-config-ui-x
sudo npm rebuild --unsafe-perm`

Any ideas?
